package ProdutosApp;


/**
* ProdutosApp/_ProdutosImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Produtos.idl
* Thursday, September 24, 2026 3:33:01 AM UTC
*/

public abstract class _ProdutosImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements ProdutosApp.Produtos, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ProdutosImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("listarProdutos", new java.lang.Integer (0));
    _methods.put ("alterarQuantidade", new java.lang.Integer (1));
    _methods.put ("alterarPreco", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ProdutosApp/Produtos/listarProdutos
       {
         ProdutosApp.Produto $result[] = null;
         $result = this.listarProdutos ();
         out = $rh.createReply();
         ProdutosApp.ListaProdutosHelper.write (out, $result);
         break;
       }

       case 1:  // ProdutosApp/Produtos/alterarQuantidade
       {
         String nome = in.read_string ();
         int quantidade = in.read_long ();
         this.alterarQuantidade (nome, quantidade);
         out = $rh.createReply();
         break;
       }

       case 2:  // ProdutosApp/Produtos/alterarPreco
       {
         String nome = in.read_string ();
         double preco = in.read_double ();
         this.alterarPreco (nome, preco);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ProdutosApp/Produtos:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ProdutosImplBase
