package ProdutosApp;


/**
* ProdutosApp/ListaProdutosHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Produtos.idl
* Thursday, September 24, 2026 3:33:01 AM UTC
*/

abstract public class ListaProdutosHelper
{
  private static String  _id = "IDL:ProdutosApp/ListaProdutos:1.0";

  public static void insert (org.omg.CORBA.Any a, ProdutosApp.Produto[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProdutosApp.Produto[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ProdutosApp.ProdutoHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ProdutosApp.ListaProdutosHelper.id (), "ListaProdutos", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProdutosApp.Produto[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ProdutosApp.Produto value[] = null;
    int _len0 = istream.read_long ();
    value = new ProdutosApp.Produto[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ProdutosApp.ProdutoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProdutosApp.Produto[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ProdutosApp.ProdutoHelper.write (ostream, value[_i0]);
  }

}
