package ProdutosApp;


/**
* ProdutosApp/ListaProdutosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Produtos.idl
* Thursday, September 24, 2026 3:33:01 AM UTC
*/

public final class ListaProdutosHolder implements org.omg.CORBA.portable.Streamable
{
  public ProdutosApp.Produto value[] = null;

  public ListaProdutosHolder ()
  {
  }

  public ListaProdutosHolder (ProdutosApp.Produto[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProdutosApp.ListaProdutosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProdutosApp.ListaProdutosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProdutosApp.ListaProdutosHelper.type ();
  }

}
