package ProdutosApp;

/**
* ProdutosApp/ProdutosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Produtos.idl
* Thursday, September 24, 2026 3:33:01 AM UTC
*/

public final class ProdutosHolder implements org.omg.CORBA.portable.Streamable
{
  public ProdutosApp.Produtos value = null;

  public ProdutosHolder ()
  {
  }

  public ProdutosHolder (ProdutosApp.Produtos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProdutosApp.ProdutosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProdutosApp.ProdutosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProdutosApp.ProdutosHelper.type ();
  }

}
