package ProdutosApp;


/**
* ProdutosApp/Produto.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Produtos.idl
* Thursday, September 24, 2026 3:33:01 AM UTC
*/

public final class Produto implements org.omg.CORBA.portable.IDLEntity
{
  public String nome = null;
  public int quantidade = (int)0;
  public double preco = (double)0;

  public Produto ()
  {
  } // ctor

  public Produto (String _nome, int _quantidade, double _preco)
  {
    nome = _nome;
    quantidade = _quantidade;
    preco = _preco;
  } // ctor

} // class Produto
