package ProdutosApp;


/**
* ProdutosApp/ProdutoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Produtos.idl
* Thursday, September 24, 2026 3:33:01 AM UTC
*/

abstract public class ProdutoHelper
{
  private static String  _id = "IDL:ProdutosApp/Produto:1.0";

  public static void insert (org.omg.CORBA.Any a, ProdutosApp.Produto that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProdutosApp.Produto extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "nome",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "quantidade",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[2] = new org.omg.CORBA.StructMember (
            "preco",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ProdutosApp.ProdutoHelper.id (), "Produto", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProdutosApp.Produto read (org.omg.CORBA.portable.InputStream istream)
  {
    ProdutosApp.Produto value = new ProdutosApp.Produto ();
    value.nome = istream.read_string ();
    value.quantidade = istream.read_long ();
    value.preco = istream.read_double ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProdutosApp.Produto value)
  {
    ostream.write_string (value.nome);
    ostream.write_long (value.quantidade);
    ostream.write_double (value.preco);
  }

}
