package ProdutosApp;


/**
* ProdutosApp/ProdutosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Produtos.idl
* Thursday, September 24, 2026 3:33:01 AM UTC
*/

public interface ProdutosOperations 
{
  ProdutosApp.Produto[] listarProdutos ();
  void alterarQuantidade (String nome, int quantidade);
  void alterarPreco (String nome, double preco);
} // interface ProdutosOperations
