package ProdutosApp;

/**
* ProdutosApp/ProdutoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Produtos.idl
* Thursday, September 24, 2026 3:33:01 AM UTC
*/

public final class ProdutoHolder implements org.omg.CORBA.portable.Streamable
{
  public ProdutosApp.Produto value = null;

  public ProdutoHolder ()
  {
  }

  public ProdutoHolder (ProdutosApp.Produto initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProdutosApp.ProdutoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProdutosApp.ProdutoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProdutosApp.ProdutoHelper.type ();
  }

}
