package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Thursday, September 24, 2026 3:14:31 AM UTC
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
