package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Thursday, September 24, 2026 3:23:30 AM UTC
*/

public interface CalculadoraOperations 
{
  double somar (double numero1, double numero2);
  double subtrair (double numero1, double numero2);
  double multiplicar (double numero1, double numero2);
  double dividir (double numero1, double numero2);
} // interface CalculadoraOperations
