package CalculadoraApp;


/**
* CalculadoraApp/Calculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Thursday, September 24, 2026 3:23:30 AM UTC
*/

public interface Calculadora extends CalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculadora
